const packs = {
  legal_reasoning: { label: 'LEGAL REASONING', title: 'The cyclist at the blind corner', scenario: 'A delivery driver checks his phone while approaching a blind corner and hits a cyclist who enters the road. The cyclist suffers a fractured wrist. Which principle best determines whether the driver is liable?', options: ['The driver is liable because an injury occurred.', 'The driver is not liable because the cyclist entered the road.', 'Liability depends on duty, breach, causation, and foreseeability.', 'Only the cyclist’s insurance determines liability.'] },
  cloud_architecture: { label: 'CLOUD SCENARIOS', title: 'The region that went quiet', scenario: 'A payments service runs every instance in one availability zone. A zone outage takes the service offline for two hours. Which design principle best addresses the root failure?', options: ['Increase the instance size in the same zone.', 'Distribute workloads across independent availability zones.', 'Add more application logs to the existing instances.', 'Move the database to a faster disk.'] }
};

let selectedPack = 'legal_reasoning';
let selectedOption = null;
let transcriptLines = [];
let recognition = null;
const $ = (id) => document.getElementById(id);
const views = { start: $('startView'), viva: $('vivaView'), result: $('resultView') };

function showView(name) { Object.values(views).forEach((view) => view.classList.add('hidden')); views[name].classList.remove('hidden'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderQuestion() { const pack = packs[selectedPack]; $('packLabel').textContent = pack.label; $('questionTitle').textContent = pack.title; $('questionScenario').textContent = pack.scenario; $('optionsList').innerHTML = pack.options.map((option, index) => `<button class="option" data-option="${index}"><span class="option-key">${String.fromCharCode(65 + index)}</span><span>${option}</span></button>`).join(''); document.querySelectorAll('.option').forEach((button) => button.addEventListener('click', () => { selectedOption = Number(button.dataset.option); document.querySelectorAll('.option').forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); setState('Ready to hear your reasoning', 'Tap the mic or type below.'); })); }
function setState(title, subtitle) { $('stateTitle').textContent = title; $('stateSubtitle').textContent = subtitle; }
function addTranscript(speaker, text) { if ($('transcript').querySelector('.transcript-empty')) $('transcript').innerHTML = ''; transcriptLines.push({ speaker, text }); const line = document.createElement('div'); line.className = `transcript-line ${speaker.toLowerCase()}`; line.innerHTML = `<label>${speaker === 'student' ? 'You' : 'Examiner'}</label>${text}`; $('transcript').appendChild(line); $('transcript').scrollTop = $('transcript').scrollHeight; }
function startViva() { selectedOption = null; transcriptLines = []; renderQuestion(); $('transcript').innerHTML = '<div class="transcript-empty"><span>◌</span><p>Your reasoning will appear here.</p><small>Take your time. A thoughtful pause is part of the viva.</small></div>'; showView('viva'); setState('Ready when you are', 'Choose an option, then explain your reasoning out loud.'); }
function processAnswer(text) { if (!text.trim()) return; addTranscript('student', text.trim()); $('answerInput').value = ''; setState('Thinking', 'I am checking the logic behind your answer.'); $('micLabel').textContent = 'Reasoning captured'; setTimeout(() => { addTranscript('examiner', 'You chose the right option. Now change one fact: if the harm was not reasonably foreseeable, would liability still be automatic?'); setState('Challenging', 'One decisive fact changed. Defend your reasoning.'); $('micLabel').textContent = 'Answer the counter-question'; }, 850); }
function finishViva() { const isCloud = selectedPack === 'cloud_architecture'; $('resultKicker').textContent = `VIVA COMPLETE · ${packs[selectedPack].label}`; if (isCloud) { $('missingConcept').firstChild.textContent = 'FAULT TOLERANCE '; $('missingDescription').textContent = 'A larger machine cannot remove a zone-level failure. Resilience comes from independent failure domains.'; $('evidenceQuote').textContent = '“Adding more capacity in the same zone should prevent the outage.”'; $('betterReasoning').innerHTML = 'Separate failure domains: <strong>replicate</strong> → <strong>distribute</strong> → <strong>recover</strong>.'; $('verdictSubtitle').textContent = 'You identified the need for capacity, but missed the failure boundary that makes the design resilient.'; } else { $('missingConcept').firstChild.textContent = 'FORESEEABILITY '; $('missingDescription').textContent = 'Not every injury creates liability. The harm must be a reasonably foreseeable result of the breach.'; $('evidenceQuote').textContent = '“If someone gets injured, the driver is automatically responsible.”'; $('betterReasoning').innerHTML = 'Test the chain: <strong>duty</strong> → <strong>breach</strong> → <strong>causation</strong> → <strong>foreseeability</strong>.'; $('verdictSubtitle').textContent = 'You identified the duty, but missed the condition that makes liability follow.'; } showView('result'); }
function setupSpeech() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) return; recognition = new SpeechRecognition(); recognition.lang = 'en-US'; recognition.interimResults = false; recognition.onstart = () => { $('micButton').classList.add('listening'); $('micLabel').textContent = 'Listening...'; setState('Listening', 'Take your time. I will wait for the end of your thought.'); }; recognition.onend = () => $('micButton').classList.remove('listening'); recognition.onresult = (event) => processAnswer(event.results[0][0].transcript); recognition.onerror = () => { $('micButton').classList.remove('listening'); setState('Ready to try again', 'Speech input was unavailable. You can type your answer below.'); }; }

document.querySelectorAll('.pack-card').forEach((card) => card.addEventListener('click', () => { selectedPack = card.dataset.pack; document.querySelectorAll('.pack-card').forEach((item) => item.classList.remove('selected')); card.classList.add('selected'); }));
$('startButton').addEventListener('click', startViva); $('brandButton').addEventListener('click', () => showView('start')); $('backButton').addEventListener('click', () => showView('start')); $('resultBackButton').addEventListener('click', () => showView('start')); $('tryAgainButton').addEventListener('click', startViva); $('endButton').addEventListener('click', finishViva);
$('answerForm').addEventListener('submit', (event) => { event.preventDefault(); processAnswer($('answerInput').value); }); $('micButton').addEventListener('click', () => { if (recognition) { if ($('micButton').classList.contains('listening')) recognition.stop(); else recognition.start(); } else { $('answerInput').focus(); setState('Text fallback ready', 'Your browser does not expose speech input here.'); } }); setupSpeech();